version: '2.4'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: smartHomeSimulator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    image: org.smart.house.simulator:0.1.0
    container_name: songservice
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8001:8080"

volumes:
  database: {}
